FROM node:21-slim as build_image

WORKDIR /home/node/app

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build


FROM node:21-slim as build_production

WORKDIR /home/node/app

COPY --from=build_image /home/node/app/node_modules /home/node/app/node_modules

COPY --from=build_image /home/node/app/dist /home/node/app/dist

COPY package.json .

COPY vite.config.ts .

EXPOSE 5173

CMD [ "npm", "run", "preview" ]



